### ISSUE TITLE
INQUIRYMODE class does not include all valid modes

### ISSUE THREAD

**Issue by Egoyibo** [Kount/kount-ris-python-sdk#9]
https://github.com/Kount/kount-ris-python-sdk/blob/44d69449d593a067a1ec656d19ca192bf16ca7c9/kount/inquiry.py#L89

Hey @danibudi! Wanted to point your attention to the INQUIRYMODE class definition ([here](https://github.com/Kount/kount-ris-python-sdk/blob/d73e90edb798c587d5d74030bba50462b8bd35cc/kount/request.py#L103-L113)). It doesn't include the update inquiry mode, and so is failing at this point. 

I'm bypassing this issue by setting the mode directly on the `params` dict

**Comment by boyankukushev** [comment]
Hey @Egoyibo!
I believe the 'missing' update modes are defined in the `UPDATEMODE` class defined [on line 346](https://github.com/Kount/kount-ris-python-sdk/blob/d73e90edb798c587d5d74030bba50462b8bd35cc/kount/request.py#L346).
Those are separated from regular Inquiry modes because they represent another type of actions for the RIS API.
Please, let us know if this is a solution to your issue, or go into deeper detail if not.
Thanks!

**Comment by Egoyibo** [comment]
@boyankukushev thanks for the prompt response.

Ah, that explains the other errors I'm getting. I'll update my code to use the `Update` class for the update call instead.
